server:
  port: 8080

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://localhost:8082
          predicates:
            - Path=/orders/** 
        - id: marketing
          uri: http://localhost:8083
          predicates:
            - Path=/marketings/** 
        - id: delivery
          uri: http://localhost:8081
          predicates:
            - Path=/deliveries/** 
        - id: warehouse
          uri: http://localhost:8084
          predicates:
            - Path=/warehouses/** 
        - id: dashboard
          uri: http://localhost:8085
          predicates:
            - Path=/dashboards/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            # allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/orders/** 
        - id: delivery
          uri: http://delivery:8080
          predicates:
            - Path=/deliveries/** 
        - id: marketing
          uri: http://marketing:8080
          predicates:
            - Path=/marketings/** 
        - id: warehouse
          uri: http://warehouse:8080
          predicates:
            - Path=/warehouses/** 
        - id: dashboard
          uri: http://dashboard:8080
          predicates:
            - Path=/dashboards/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            # allowCredentials: true

server:
  port: 8080
